### ISSUE TITLE
How to change Colors?

### ISSUE THREAD

**Issue by HugoMatilla** [fBosch/vscode-battery-indicator#1]
Hi, 

first, thank you for your work.

Second, how do I change the colors? I see on the readme that you added setting for that, but I can't find how?

Thank you in advance.

**Comment by fbosch** [comment]
Hey, 

Glad you enjoy it 🤠

I had a todo list of features I might do in the README.

I have removed that section to avoid further confusion, I won't be updating this plugin any time soon — sorry for the inconvenience
